name: Use Organization AI Commit Checker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ai_commit_check:
    uses: turing-test-workflow/org-workflows/.github/workflows/ai-commit-checker.yml@main
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
